---
- name: register and enable epel repository
  yum: name=epel-release state=present

- name: install java 8 (headless)
  yum: name=java-1.8.0-openjdk-headless state=latest update_cache=true
  when: headless

- name: install java 8 (full)
  yum: name=java-1.8.0-openjdk-devel state=latest update_cache=true
  when: not headless

- name: link the default jdk path
  file:
    src: /usr/lib/jvm/jre-1.8.0-openjdk
    dest: "{{default_path}}"
    state: link
    force: yes
