---
- name: include redhat family
  include: centos.yml
  when: ansible_os_family == 'RedHat'

- name: include debian family
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: set JAVA_HOME as a system wide environment variable
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^JAVA_HOME"
    line: "JAVA_HOME={{default_path}}"
